-- Table for World
CREATE TABLE world (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    dungeon_capacity INT,
    guild_capacity INT
);

-- Table for Dungeon
CREATE TABLE dungeon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    monster_capacity INT,
    party_capacity INT,
    level INT,
    gold_reward INT,
    world_id BIGINT REFERENCES world(id)
);

-- Table for Monster
CREATE TABLE monster (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    level INT,
    health INT,
    dungeon_id BIGINT REFERENCES dungeon(id)
);

-- Table for Guild
CREATE TABLE guild (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    player_capacity INT,
    rank INT,
    gold INT,
    world_id BIGINT REFERENCES world(id)
);

-- Table for Hero
CREATE TABLE hero (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    power INT,
    health INT,
    guild_id BIGINT REFERENCES guild(id)
);
